# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
