# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160421_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 21, 2, 55, 46, 174255, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
