# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_datestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datestamp',
            field=models.DateField(),
        ),
    ]
